#INTRA VARIATION PLOT

#BEES
##graphed three for aesthetics based on size range
par(mfrow=c(2,3))
par(pty="s")
plot(HU_IT,main="Homalictus urbanus",ylab = "ITD (mm)",xlab="")
abline(a=HU_IT[251],b=0,col=2)
abline(a=confint(lm(bee_species$Homalictus_urbanus$IT~1))[1],b=0,col=3)
abline(a=confint(lm(bee_species$Homalictus_urbanus$IT~1))[2],b=0,col=3)
#plot(LP_IT,main="Lasioglossum pauxillum",ylab = "",xlab="")
plot(AF_IT,main="Andrena flavipes",ylab = "",xlab="")
abline(a=AF_IT[75],b=0,col=2)
abline(a=confint(lm(bee_species$Andrena_flavipes$IT~1))[1],b=0,col=3)
abline(a=confint(lm(bee_species$Andrena_flavipes$IT~1))[2],b=0,col=3)
plot(BL_IT,main="Bombus lucorum",ylab = "",xlab="")
abline(a=BL_IT[111],b=0,col=2)
abline(a=confint(lm(bee_species$Bombus_lucorum$IT~1))[1],b=0,col=3)
abline(a=confint(lm(bee_species$Bombus_lucorum$IT~1))[2],b=0,col=3)

#plot(LL_IT,main="Lasioglossum lanarium",ylab = "",xlab="Sample size")

plot(HU_WT,ylab = "Specimen weight (mg)",xlab="Sample size")
abline(a=HU_WT[251],b=0,col=2)
abline(a=confint(lm(bee_species$Homalictus_urbanus$Spec.wgt~1))[1],b=0,col=3)
abline(a=confint(lm(bee_species$Homalictus_urbanus$Spec.wgt~1))[2],b=0,col=3)
#plot(LP_WT,ylab = "",xlab="Sample size")
plot(AF_WT,ylab = "",xlab="Sample size")
abline(a=AF_WT[75],b=0,col=2)
abline(a=confint(lm(bee_species$Andrena_flavipes$Spec.wgt~1))[1],b=0,col=3)
abline(a=confint(lm(bee_species$Andrena_flavipes$Spec.wgt~1))[2],b=0,col=3)

plot(BL_WT,ylab = "",xlab="Sample size")
abline(a=BL_WT[111],b=0,col=2)
abline(a=confint(lm(bee_species$Bombus_lucorum$Spec.wgt~1))[1],b=0,col=3)
abline(a=confint(lm(bee_species$Bombus_lucorum$Spec.wgt~1))[2],b=0,col=3)
#plot(LL_WT,ylab = "",xlab="Sample size")


##HOVERFLIES
##graphed three for aesthetics based on size range
par(mfrow=c(2,3))
par(pty="s")
plot(HHP_IT,main="Helophilus parallelus",ylab = "ITD (mm)",xlab="",ylim=c(3.6,4))
abline(a=HHP_IT[19],b=0,col=2)
abline(a=confint(lm(hov_species$Helophilus_parallelus$IT~1))[1],b=0,col=3)
abline(a=confint(lm(hov_species$Helophilus_parallelus$IT~1))[2],b=0,col=3)
plot(HSM_IT,main="Sphaerophoria macrogaster",ylab = "",xlab="",ylim=c(1.1,1.5))
abline(a=HSM_IT[17],b=0,col=2)
abline(a=confint(lm(hov_species$Sphaerophoria_macrogaster$IT~1))[1],b=0,col=3)
abline(a=confint(lm(hov_species$Sphaerophoria_macrogaster$IT~1))[2],b=0,col=3)
plot(HEB_IT,main="Episyrphus balteatus",ylab = "",xlab="Sample size",ylim=c(2.1,2.55))
abline(a=HEB_IT[15],b=0,col=2)
abline(a=confint(lm(hov_species$Episyrphus_balteatus$IT~1))[1],b=0,col=3)
abline(a=confint(lm(hov_species$Episyrphus_balteatus$IT~1))[2],b=0,col=3)
#plot(HMM_IT,main="Melanostoma_mellinum",ylab = "",xlab="")
#plot(HSP_IT,main="Syritta_pipiens",ylab = "",xlab="Sample size")

plot(HHP_WT,ylab = "Specimen weight (mg)",xlab="Sample size",ylim=c(32,42))
abline(a=HHP_WT[19],b=0,col=2)
abline(a=confint(lm(hov_species$Helophilus_parallelus$Spec.wgt~1))[1],b=0,col=3)
abline(a=confint(lm(hov_species$Helophilus_parallelus$Spec.wgt~1))[2],b=0,col=3)
plot(HSM_WT,ylab = "",xlab="Sample size")
abline(a=HSM_WT[17],b=0,col=2)
abline(a=confint(lm(hov_species$Sphaerophoria_macrogaster$Spec.wgt~1))[1],b=0,col=3)
abline(a=confint(lm(hov_species$Sphaerophoria_macrogaster$Spec.wgt~1))[2],b=0,col=3)
plot(HEB_WT,ylab = "",xlab="Sample size",ylim=c(4,12))
abline(a=HEB_WT[15],b=0,col=2)
abline(a=confint(lm(hov_species$Episyrphus_balteatus$Spec.wgt~1))[1],b=0,col=3)
abline(a=confint(lm(hov_species$Episyrphus_balteatus$Spec.wgt~1))[2],b=0,col=3)
#plot(HMM_WT,ylab = "",xlab="Sample size")
#plot(HSP_WT,ylab = "",xlab="Sample size")